FORMAT: 1A
HOST: http://www.identity-and-access.de/api/v1

# Identity and Access API

RESTful API to create, update and read tenants, identities and roles in context.

# Group tenants

## register [POST /tenant]

Registers a new tenant.

+ Parameters
  + tenantName: `MyTenant` (string, required) - The name of the tenant, must be unique

+ Response 200 (text/plain)
	OK

# Group identities

# Group roles in context
